import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";

// See .claude/tests/00-conventions.md for the reasoning behind this setup
// (two projects, DB-of-test safety guard, Next.js API mocks, coverage
// thresholds).
export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: [
        "app/**/*.{ts,tsx}",
        "features/**/*.{ts,tsx}",
        "lib/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
      ],
      exclude: [
        "components/ui/**", // generated by shadcn, not project logic
        "prisma/migrations/**",
        "prisma/seed.ts",
        "tests/**",
        "**/*.config.*",
      ],
      thresholds: {
        lines: 75,
        functions: 75,
        branches: 75,
        statements: 75,
      },
    },
    projects: [
      {
        // Server Actions, lib/, Zod schemas — real test database, no DOM.
        extends: true,
        test: {
          name: "unit",
          environment: "node",
          include: ["tests/unit/**/*.test.ts"],
          setupFiles: ["tests/setup/env.ts", "tests/setup/mocks.ts"],
          // Tests share a single real test database (no per-test isolation
          // like transactions), so test files run one at a time to avoid
          // races between files. A simplification, deliberate for this MVP.
          fileParallelism: false,
        },
      },
      {
        // Client Components with React Testing Library — jsdom, no DB.
        extends: true,
        test: {
          name: "integration",
          environment: "jsdom",
          include: ["tests/integration/**/*.test.tsx"],
          setupFiles: ["tests/setup/integration.setup.ts"],
        },
      },
    ],
  },
});
